server: 
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 3GB
      max-request-size: 3GB
  cloud:
    gateway:
      default-filters:
      - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "http://localhost:4200"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
      routes:
        - id: BACKEND_USER
          uri: http://localhost:8082
          predicates:
            - Path=/users/**
        - id: BACKEND_ORGANIZATION
          uri: http://localhost:8082
          predicates:
            - Path=/organizations/**
        - id: BACKEND_PROJECT
          uri: http://localhost:8082
          predicates:
            - Path=/projects/**
        - id: BACKEND_CASE
          uri: http://localhost:8082
          predicates:
            - Path=/cases/**
        - id: BACKEND_ANNOTATION
          uri: http://localhost:8081
          predicates:
            - Path=/annotations/**
        - id: BACKEND_IMAGE
          uri: http://localhost:8082
          predicates:
            - Path=/images/**
        - id: BACKEND_RESOURCE
          uri: http://localhost:8082
          predicates:
            - Path=/resources/**
        - id: BACKEND_PROJECTION
          uri: http://localhost:8083
          predicates:
            - Path=/projections/**
        - id: BACKEND_JOB
          uri: http://localhost:8084
          predicates:
            - Path=/jobs/**
        - id: BACKEND_ANALYTICS
          uri: http://localhost:5000
          predicates:
            - Path=/analytics/**
---
server:
  port: 8080

spring:
  config:
    activate:
      on-profile: avib
  servlet:
    multipart:
      max-file-size: 3GB
      max-request-size: 3GB
  cloud:
    gateway:
      default-filters:
      - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "https://avispe.edv.uniovi.es"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
      routes:
        - id: BACKEND_USER
          uri: http://avib-backend-organization:8082
          predicates:
            - Path=/users/**
        - id: BACKEND_ORGANIZATION
          uri: http://avib-backend-organization:8082
          predicates:
            - Path=/organizations/**
        - id: BACKEND_PROJECT
          uri: http://avib-backend-organization:8082
          predicates:
            - Path=/projects/**
        - id: BACKEND_CASE
          uri: http://avib-backend-organization:8082
          predicates:
            - Path=/cases/**
        - id: BACKEND_ANNOTATION
          uri: http://avib-backend-annotation:8081
          predicates:
            - Path=/annotations/**
        - id: BACKEND_IMAGE
          uri: http://avib-backend-organization:8082
          predicates:
            - Path=/images/**
        - id: BACKEND_RESOURCE
          uri: http://avib-backend-organization:8082
          predicates:
            - Path=/resources/**
        - id: BACKEND_PROJECTION
          uri: http://avib-backend-storage:8083
          predicates:
            - Path=/projections/**
        - id: BACKEND_JOB
          uri: http://avib-backend-organization:8082
          predicates:
            - Path=/jobs/**
        - id: BACKEND_ANALYTICS
          uri: http://avib-backend-analytics:5000
          predicates:
            - Path=/analytics/**